<?php

/**
 * @file
 * OCHA Azure tweaks.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ocha_azure_tweaks_form_openid_connect_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('ocha_azure_tweaks.settings');

  $register_client_id = $config->get('openid_register_client');
  $reset_client_id = $config->get('openid_reset_client');

  unset($form['openid_connect_client_' . $register_client_id . '_login']);
  unset($form['openid_connect_client_' . $reset_client_id . '_login']);
}
