ocha_azure_tweaks.settings:
  type: config_object
  label: 'OCHA Azure tweaks settings'
  mapping:
    disable_user_create:
      type: bool
      label: 'Disable user create form'
    openid_connect_client_id:
      type: string
      label: 'OpenID Client ID'
    password_url:
      type: string
      label: 'Password reset url'
    register_url:
      type: string
      label: 'Register URL'
    redirect_endpoint:
      type: string
      label: 'Redirect Endpoint'
