ocha_azure_tweaks.settings:
  type: config_object
  label: 'OCHA Azure tweaks settings'
  mapping:
    disable_user_create:
      type: bool
      label: 'Disable user create form'
    openid_register_client:
      type: string
      label: 'OpenID Client ID'
    openid_reset_client:
      type: string
      label: 'OpenID Client ID'
